# shellcheck shell=bash
# Auto-generated by "{{.CommandName}} install bash".

_{{.CommandName}}_complete() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"

  local subcommands="install completion"
  local shell_targets="nushell zsh bash"
  local flags="-v --verbose -n --dry-run -m --model -p --prompt -e --edit-prompt --gps --exif --clear -h --help --version"

  if [[ ${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${subcommands}" -- "${cur}") $(compgen -f -- "${cur}") )
    return 0
  fi

  local first="${COMP_WORDS[1]}"
  if [[ "${first}" == "install" || "${first}" == "completion" ]]; then
    if [[ ${COMP_CWORD} -eq 2 ]]; then
      COMPREPLY=( $(compgen -W "${shell_targets}" -- "${cur}") )
      return 0
    fi
    return 0
  fi

  if [[ "${cur}" == -* ]]; then
    COMPREPLY=( $(compgen -W "${flags}" -- "${cur}") )
    return 0
  fi

  COMPREPLY=( $(compgen -f -- "${cur}") )
}

complete -F _{{.CommandName}}_complete {{.CommandName}}
