package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

func nushellAutoloadDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home directory: %w", err)
	}

	switch runtime.GOOS {
	case "darwin":
		return filepath.Join(home, "Library", "Application Support", "nushell", "vendor", "autoload"), nil
	case "windows":
		appData := strings.TrimSpace(os.Getenv("APPDATA"))
		if appData == "" {
			appData = filepath.Join(home, "AppData", "Roaming")
		}
		return filepath.Join(appData, "nushell", "vendor", "autoload"), nil
	default:
		config := strings.TrimSpace(os.Getenv("XDG_CONFIG_HOME"))
		if config == "" {
			config = filepath.Join(home, ".config")
		}
		return filepath.Join(config, "nushell", "vendor", "autoload"), nil
	}
}

func renderNushellModule(commandName string) string {
	return fmt.Sprintf(`# Auto-generated by "cr3 install nushell".
#
# Note: Nushell extern signatures cannot model optional flag values.
# --gps is typed as requiring a path in this module. If you want the CLI's
# default GPX behavior, pass: --gps ~/.cr3-keywords/track.gpx

export extern %q [
  --verbose(-v)      # Print detailed per-file logs
  --dry-run(-n)      # Simulate actions without writing files or sending requests
  --model(-m): string # Optional model name
  --prompt(-p): path # Prompt file path
  --edit-prompt(-e)  # Open prompt file in terminal editor before running
  --gps: path        # GPX track file path
  --exif             # Force exiftool for CR3 preview extraction
  --clear            # Delete generated .jpg/.txt and sidecar .xmp files
  --help(-h)         # Show help
  --version          # Show version and exit
  cr3_path?: string@"nu-complete cr3 dirs"
  ...files: string@"nu-complete cr3 files"
]

export extern %q [
  target: string@"nu-complete cr3 shell-target"
]

export extern %q [
  target: string@"nu-complete cr3 shell-target"
]

export def "nu-complete cr3 shell-target" [] {
  ["nushell", "zsh", "bash"]
}

def "nu-complete cr3 dirs" [context: string] {
  let parts = ($context | split row " " | where { |p| $p != "" })
  let token = if ($context | str ends-with " ") {
    ""
  } else if ($parts | is-empty) {
    ""
  } else {
    $parts | last
  }

  let token_has_sep = ($token | str ends-with "/")

  let base_dir = if ($token == "") {
    "."
  } else if $token_has_sep {
    $token
  } else {
    let d = ($token | path dirname)
    if ($d == "") { "." } else { $d }
  }

  let prefix = if ($token == "" or $token_has_sep) {
    ""
  } else {
    $token | path basename
  }

  try {
    let dirs = (
      ls -a $base_dir
      | where type == dir
      | where { |row|
          let name = ($row.name | path basename)
          (not ($name | str starts-with ".")) and (($name | str downcase) | str starts-with ($prefix | str downcase))
        }
      | get name
    )

    let values = if ($base_dir == ".") {
      $dirs | each { |p| $p | path basename }
    } else {
      $dirs
    }

    {
      options: {
        case_sensitive: false,
        completion_algorithm: prefix,
      },
      completions: $values
    }
  } catch {
    []
  }
}

def "nu-complete cr3 files" [context: string] {
  let parts = ($context | split row " " | where { |p| $p != "" })
  if ($parts | length) < 2 {
    []
  } else {
    let sub = ($parts | get 1)
    if ($sub == "install" or $sub == "completion") {
      []
    } else {
      let positional = (
        $parts
        | skip 1
        | where { |p| not ($p | str starts-with "-") }
      )

      if ($positional | is-empty) {
        []
      } else {
        let cr3_dir = ($positional | first)
        let file_prefix = if ($context | str ends-with " ") {
          ""
        } else {
          let last = ($parts | last)
          if ($last == $cr3_dir) { "" } else { $last | path basename }
        }

        try {
          let files = (
            ls -a $cr3_dir
            | where type == file
            | where { |row|
                let name = ($row.name | path basename)
                (($name | str downcase) | str ends-with ".cr3") and (($name | str downcase) | str starts-with ($file_prefix | str downcase))
              }
            | get name
            | each { |p| $p | path basename }
          )

          {
            options: {
              case_sensitive: false,
              completion_algorithm: prefix,
            },
            completions: $files
          }
        } catch {
          []
        }
      }
    }
  }
}
`, commandName, commandName+" install", commandName+" completion")
}
