# Auto-generated by "{{.CommandName}} install nushell".
#
# Note: Nushell extern signatures cannot model optional flag values.
# --gps is typed as requiring a path in this module. If you want the CLI's
# default GPX behavior, pass: --gps ~/.cr3-keywords/track.gpx

export extern "{{.CommandName}}" [
  --verbose(-v)       # Print detailed per-file logs
  --dry-run(-n)       # Simulate actions without writing files or sending requests
  --model(-m): string # Optional model name
  --prompt(-p): path  # Prompt file path
  --edit-prompt(-e)   # Open prompt file in terminal editor before running
  --gps: path         # GPX track file path
  --exif              # Force exiftool for CR3 preview extraction
  --clear             # Delete generated .jpg/.txt and sidecar .xmp files
  --help(-h)          # Show help
  --version           # Show version and exit
  cr3_path?: string@"nu-complete {{.CommandName}} dirs"
  ...files: string@"nu-complete {{.CommandName}} files"
]

export extern "{{.CommandName}} install" [
  target: string@"nu-complete {{.CommandName}} shell-target"
]

export extern "{{.CommandName}} completion" [
  target: string@"nu-complete {{.CommandName}} shell-target"
]

# Prefer man page content when available so `help {{.CommandName}}` is close to Unix `man {{.CommandName}}`.
export def "help {{.CommandName}}" [] {
  let has_man = ((which man | length) > 0)
  if $has_man {
    try {
      ^man {{.CommandName}}
    } catch {
      ^{{.CommandName}} --help
    }
  } else {
    ^{{.CommandName}} --help
  }
}

export def "nu-complete {{.CommandName}} shell-target" [] {
  ["nushell", "zsh", "bash"]
}

def "nu-complete {{.CommandName}} examples" [] {
  [
    { value: "~/Pictures/Canon --gps ~/.cr3-keywords/track.gpx --exif" description: "Recommended default for geotagged Canon batches with reliable exiftool extraction" }
    { value: "~/Pictures/Canon --gps ~/.cr3-keywords/track.gpx --exif --edit-prompt" description: "Same workflow, but open and tune the prompt before generating captions/keywords" }
    { value: "~/Pictures/Canon --gps ~/.cr3-keywords/track.gpx --exif --edit-prompt --model llava --prompt ~/.cr3-keywords/prompt.txt" description: "Fully controlled run: fixed model, curated prompt, and in-session prompt edits" }
    { value: "~/Pictures/Canon --verbose --dry-run" description: "Test mode with detailed logs to verify behavior before writing any output files" }
    { value: "~/Pictures/Canon --clear" description: "Cleanup pass that removes generated JPG/TXT/XMP artifacts for this folder" }
  ]
}

def "nu-complete {{.CommandName}} dirs" [context: string] {
  let parts = ($context | split row " " | where { |p| $p != "" })
  let token = if ($context | str ends-with " ") {
    ""
  } else if ($parts | is-empty) {
    ""
  } else {
    $parts | last
  }

  let token_has_sep = ($token | str ends-with "/")

  let base_dir = if ($token == "") {
    "."
  } else if $token_has_sep {
    $token
  } else {
    let d = ($token | path dirname)
    if ($d == "") { "." } else { $d }
  }

  let prefix = if ($token == "" or $token_has_sep) {
    ""
  } else {
    $token | path basename
  }

  try {
    let dirs = (
      ls -a $base_dir
      | where type == dir
      | where { |row|
          let name = ($row.name | path basename)
          (not ($name | str starts-with ".")) and (($name | str downcase) | str starts-with ($prefix | str downcase))
        }
      | get name
    )

    let values = if ($base_dir == ".") {
      $dirs | each { |p| $p | path basename }
    } else {
      $dirs
    }

    let show_examples = (($parts | length) <= 1) and ($context | str ends-with " ")
    let completions = if $show_examples {
      let dir_records = ($values | each { |v| { value: $v } })
      (nu-complete {{.CommandName}} examples) ++ $dir_records
    } else {
      $values
    }

    {
      options: {
        case_sensitive: false,
        completion_algorithm: prefix,
      },
      completions: $completions
    }
  } catch {
    []
  }
}

def "nu-complete {{.CommandName}} files" [context: string] {
  let parts = ($context | split row " " | where { |p| $p != "" })
  if ($parts | length) < 2 {
    []
  } else {
    let sub = ($parts | get 1)
    if ($sub == "install" or $sub == "completion") {
      []
    } else {
      let positional = (
        $parts
        | skip 1
        | where { |p| not ($p | str starts-with "-") }
      )

      if ($positional | is-empty) {
        []
      } else {
        let cr3_dir = ($positional | first)
        let file_prefix = if ($context | str ends-with " ") {
          ""
        } else {
          let last = ($parts | last)
          if ($last == $cr3_dir) { "" } else { $last | path basename }
        }

        try {
          let files = (
            ls -a $cr3_dir
            | where type == file
            | where { |row|
                let name = ($row.name | path basename)
                (($name | str downcase) | str ends-with ".cr3") and (($name | str downcase) | str starts-with ($file_prefix | str downcase))
              }
            | get name
            | each { |p| $p | path basename }
          )

          {
            options: {
              case_sensitive: false,
              completion_algorithm: prefix,
            },
            completions: $files
          }
        } catch {
          []
        }
      }
    }
  }
}
