package shell

import "fmt"

func renderZshCompletion(commandName string) string {
	return fmt.Sprintf(`#compdef %[1]s
# Auto-generated by "cr3 install zsh".

local -a shell_targets
shell_targets=(
  'nushell:Nushell module'
  'zsh:Zsh completion'
  'bash:Bash completion'
)

if (( CURRENT == 2 )); then
  _alternative \
    'subcommand:subcommand:(install completion)' \
    'path:path:_files'
  return
fi

case "${words[2]}" in
  install|completion)
    _describe 'shell target' shell_targets
    ;;
  *)
    _arguments -S \
      '(-v --verbose)'{-v,--verbose}'[Print detailed per-file logs]' \
      '(-n --dry-run)'{-n,--dry-run}'[Simulate actions without writing files or sending requests]' \
      '(-m --model)'{-m,--model}'[Optional model name]:model name:' \
      '(-p --prompt)'{-p,--prompt}'[Prompt file path]:prompt file:_files' \
      '(-e --edit-prompt)'{-e,--edit-prompt}'[Open prompt file in terminal editor before running]' \
      '--gps[Enable GPX geotagging]:gpx file:_files' \
      '--exif[Force exiftool for CR3 preview extraction]' \
      '--clear[Delete generated .jpg/.txt and sidecar .xmp files]' \
      '(-h --help)'{-h,--help}'[Show help]' \
      '--version[Show version and exit]' \
      '*:files:_files'
    ;;
esac
`, commandName)
}
